#!/bin/csh
#
#	A silly little script to Fix the Links that cvs does not
# import/ checkout.  These need to be made by the Makefiles, this
# is just here as a stop gap solution.
#
#	$Id: FixLinks,v 1.9 1994/02/05 23:53:40 rgrimes Exp $
#

pushd games/fortune/datfiles ; ln -s fortunes-o.real.rot13 fortunes-o ; popd
