#!/bin/csh -f
#  Ported to boot 386BSD by Julian Elischer (julian@tfs.com) Sept 1992
# 
#
# HISTORY
# $Log: rmaouthdr,v $
# Revision 1.2  1993/07/13 18:15:29  root
# New boot blocks, from Bruce Evans, and NetBSD fixes.  Allows kernel to
# be loaded above 1MB.  Same boot code for floppies now.  Speed improvements.
# etc etc etc. (I don't have much history on this, but then have been tested)
#
# Revision 1.1  1993/03/21  18:08:40  cgd
# after 0.2.2 "stable" patches applied
#
# Revision 2.2  92/04/04  11:36:01  rpd
# 	From 2.5 boot
# 	[92/03/30            mg32]
# 
#
dd if=$1 of=$2 ibs=32 skip=1 obs=1024b
