#	From: @(#)Makefile	5.1 (Berkeley) 6/25/90
#	$Id: Makefile,v 1.1 1994/02/25 01:13:54 wollman Exp $

PROG=	kdb_destroy
CFLAGS+=-DKERBEROS -DDEBUG -I${.CURDIR}/../include
NOMAN=	noman

.include <bsd.prog.mk>
