#	From: @(#)Makefile	5.1 (Berkeley) 6/25/90
#	$Id: Makefile,v 1.1 1994/02/25 01:13:25 wollman Exp $

LIB=	acl
CFLAGS+=-DDEBUG -DKERBEROS -I${.CURDIR}/../include
SRCS=	acl_files.c

.include <bsd.lib.mk>
